name: ZMK Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0 # Specify the latest version

      - name: Set up Zephyr environment
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            git \
            cmake \
            gperf \
            ccache \
            dfu-util \
            dtc \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            python3-dev \
            ninja-build \
            g++ \
            wget \
            unzip \
            xz-utils \
            file \
            make \
            gcc-arm-none-eabi

          # Install west tool
          pip3 install west

      - name: Initialize west and fetch modules
        run: |
          west init -l config/
          west update

      - name: Build ZMK Firmware
        run: |
          west build -b nice_nano_v2 --shield corne_left -DZMK_CONFIG=config
          west build -b nice_nano_v2 --shield corne_right -DZMK_CONFIG=config
